language: node_js
node_js:
- '6'
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: lesson-05
env:
  global:
    secure: EnCZPEyVZr1MPTF75loCBQGH2s4Y68lzJjbvJT4n4qDIXPk/2s2M1T1g9wEXMMzexgUHQsGg3mXP1ldjbEaqYVtLVkWRELmXsEO4lWkcZKiTyUPkHqIExk+sGL8Fh9QzokLuq2Kc2+1uy2HGCtT8try4z3F7fb1AdrDpPCyBFgHq6oXeM55G9zidFuYMtIf9UsdjQ3BVUXyGF3R+FJyP9fZS3Vc/muVNKpZPdST3Gr8ym9KDeNjICuu1n1pD7fPOdiAD8jl4RiHY8Jft15FVTE9+A2CSYmkfpH18NeZ3N9AhTBzT8KpAnNp2Iiubt1yLEDnnuabmfJtQ5E0Z9WOW226/3BQKVQY4vdlMalCyOpaTxWEvfaNo9QcAtMGHjAmj1ttXZG6z7QSXELwsuOPOVKZt/6wsanpaMgu6uAqkUCR43Y8glx+7as5g37tNBQMI2bXIGd0MV/Scrsrxsr3CJ0LULDPELZgBjmcT4KKQAvDTAmIIgvm/yWuvMy39qcRS8+bDwPAFp9lV0WyXPTc4DKKDpwi4ZZgRZVosIz+T70PDpKi4fkMoH10rXYVxluDehDjXP3x9mE9IRAA2lJZ8Y71qv0MiuyLl4VkSQbu7CRczcvTl0zrfVcLxnTkRfTKyRrUNYjmk4DlEGveRSoas8ShNoDkT+Z3EGp7LXMclY1Y=
